Practical Questions: 
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

transposed_array = array.T
print("Transposed Array (interchanged rows and columns):\n", transposed_array)


Original Array:
 [[56 32  9]
 [10 11 86]
 [82 19 46]]
Transposed Array (interchanged rows and columns):
 [[56 10 82]
 [32 11 19]
 [ 9 86 46]]


q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [2]:
import numpy as np

array_1d = np.arange(10)
array_2x5 = array_1d.reshape(2, 5)
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:\n", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [3]:
import numpy as np

array_4x4 = np.random.rand(4, 4)
bordered_array = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", array_4x4)
print("6x6 Array with Border of Zeros:\n", bordered_array)


Original 4x4 Array:
 [[0.0856553  0.74140857 0.7247198  0.0741415 ]
 [0.82438442 0.79851803 0.86042763 0.02616112]
 [0.74969433 0.57332057 0.91086355 0.32029442]
 [0.45213002 0.62309565 0.65692753 0.39614598]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.0856553  0.74140857 0.7247198  0.0741415  0.        ]
 [0.         0.82438442 0.79851803 0.86042763 0.02616112 0.        ]
 [0.         0.74969433 0.57332057 0.91086355 0.32029442 0.        ]
 [0.         0.45213002 0.62309565 0.65692753 0.39614598 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:\n", array)


Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [5]:
import numpy as np

array_strings = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(array_strings)
lowercase = np.char.lower(array_strings)
titlecase = np.char.title(array_strings)
capitalize = np.char.capitalize(array_strings)

print("Original Array:\n", array_strings)
print("Uppercase:\n", uppercase)
print("Lowercase:\n", lowercase)
print("Title Case:\n", titlecase)
print("Capitalized:\n", capitalize)


Original Array:
 ['python' 'numpy' 'pandas']
Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']
Capitalized:
 ['Python' 'Numpy' 'Pandas']


q6.Generate a NumPy array of words. Insert a space between each character of every word in the array

In [6]:
import numpy as np

array_words = np.array(['hello', 'numpy', 'array'])
spaced_words = np.char.join(' ', array_words)

print("Original Array:\n", array_words)
print("Words with Spaces:\n", spaced_words)


Original Array:
 ['hello' 'numpy' 'array']
Words with Spaces:
 ['h e l l o' 'n u m p y' 'a r r a y']


q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [7]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [8]:
import numpy as np

identity_matrix = np.eye(5)
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [9]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, size=100)
prime_numbers = np.array([num for num in random_array if is_prime(num)])

print("Random Array:\n", random_array)
print("Prime Numbers:\n", prime_numbers)

Random Array:
 [516 681 231 565 936 777  70 560 727 839 344 208 273 120 259 466 558 594
 653 139 854  75 611 339 438 269  67 194 632 347 938 592  92 440 315 361
 510 674 828 846 382 440 790 483 317 889 913 514 847 990 962 484  69 259
 901 546 855 993 741 680 696 210 913 753  99 796  46  85 614 133 826 332
 588 788 518 439 128 168   6 104 617 526 468 345 627 101 927 438 405 599
 339 743  98 674 402 976  78 670 649 699]
Prime Numbers:
 [727 839 653 139 269  67 347 317 439 617 101 599 743]


q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [12]:
import numpy as np

daily_temperatures = np.random.uniform(low=15, high=35, size=30)

weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures for a Month:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures for a Month:
 [24.03068128 24.671797   18.22832767 27.13738975 17.34040989 19.86345335
 32.41085915 17.99263318 22.9344657  26.73140641 34.70436604 23.3169937
 29.6766895  25.69905664 27.34685406 30.79787456 23.36090421 26.36432858
 25.00188098 26.64596162 15.38109574 30.61721347 33.05352122 22.70931491
 23.63974483 28.51296294 22.70237162 18.26861382 26.63766586 17.71704026]
Weekly Averages:
 [23.38327401 25.86508731 24.98555711 25.64339183]
